services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "my_app"
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    links:
      - "mysql_db:db"
  
  mysql_db:
    image: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=base

volumes:
  flask_proj: