services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "my_app"
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    links:
      - "mysql_db:db"
    volumes:
      -./app:./src
  
  mysql_db:
    image: 
    container_name: "books_reviews"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=reviews

volumes:
  flask_proj: