services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "my_app"
    ports:
      - "80:5000"
    depends_on:
      - mysql_db
    links:
      - "mysql_db:db"
    volumes:
      - .:/src

  mysql_db:
    image: mysql
    container_name: "books_reviews"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=reviews

  mysql_db_out:
    image: mysql
    container_name: "books_reviews_out"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=reviews
    ports:
      - "3306:3306"

volumes:
  app:
